export const READ_EXCHANGE_RATES: string = "READ_EXCHANGE_RATES";
export const READ_EXCHANGE_RATES_SUCCESS: string =
  "READ_EXCHANGE_RATES_SUCCESS";
export const READ_EXCHANGE_RATES_ERROR: string = "READ_EXCHANGE_RATES_ERROR";
